package pojo;
// Generated 01-feb-2019 0:48:51 by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pertenece generated by hbm2java
 */
@Entity
@Table(name = "pertenece", catalog = "musicaconclavesajenas")
public class Pertenece implements java.io.Serializable {

	private PerteneceId id;
	private Grupo grupo;
	private Artista artista;
	private String funcion;

	public Pertenece() {
	}

	public Pertenece(PerteneceId id, Grupo grupo, Artista artista) {
		this.id = id;
		this.grupo = grupo;
		this.artista = artista;
	}

	public Pertenece(PerteneceId id, Grupo grupo, Artista artista, String funcion) {
		this.id = id;
		this.grupo = grupo;
		this.artista = artista;
		this.funcion = funcion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dni", column = @Column(name = "dni", nullable = false, length = 10)),
			@AttributeOverride(name = "cod", column = @Column(name = "cod", nullable = false)) })
	public PerteneceId getId() {
		return this.id;
	}

	public void setId(PerteneceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod", nullable = false, insertable = false, updatable = false)
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dni", nullable = false, insertable = false, updatable = false)
	public Artista getArtista() {
		return this.artista;
	}

	public void setArtista(Artista artista) {
		this.artista = artista;
	}

	@Column(name = "funcion", length = 15)
	public String getFuncion() {
		return this.funcion;
	}

	public void setFuncion(String funcion) {
		this.funcion = funcion;
	}

}
