package pojos;
// Generated 19-ene-2016 14:06:58 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Cancion generated by hbm2java
 */
@Entity
@Table(name = "cancion", catalog = "musicaconclavesajenas")
public class Cancion implements java.io.Serializable {

	private Integer cod;
	private String titulo;
	private Double duracion;
	private Set<Disco> discos = new HashSet<Disco>(0);

	public Cancion() {
	}

	public Cancion(String titulo) {
		this.titulo = titulo;
	}

	public Cancion(String titulo, Double duracion, Set<Disco> discos) {
		this.titulo = titulo;
		this.duracion = duracion;
		this.discos = discos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cod", unique = true, nullable = false)
	public Integer getCod() {
		return this.cod;
	}

	public void setCod(Integer cod) {
		this.cod = cod;
	}

	@Column(name = "titulo", nullable = false, length = 30)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "duracion", precision = 15, scale = 5)
	public Double getDuracion() {
		return this.duracion;
	}

	public void setDuracion(Double duracion) {
		this.duracion = duracion;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "esta", catalog = "musicaconclavesajenas", joinColumns = {
			@JoinColumn(name = "can", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "cod", nullable = false, updatable = false) })
	public Set<Disco> getDiscos() {
		return this.discos;
	}

	public void setDiscos(Set<Disco> discos) {
		this.discos = discos;
	}

}
