package pojo;
// Generated 31-ene-2019 22:49:54 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name = "proyecto", catalog = "empresa")
public class Proyecto implements java.io.Serializable {

	private int num;
	private Departamento departamento;
	private String nombre;

	public Proyecto() {
	}

	public Proyecto(int num) {
		this.num = num;
	}

	public Proyecto(int num, Departamento departamento, String nombre) {
		this.num = num;
		this.departamento = departamento;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "num", unique = true, nullable = false)
	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departamento")
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@Column(name = "nombre", length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
